#!/bin/bash

rmmod meudriver 2> /dev/null

make clean

make -C /lib/modules/$(uname -r)/build M=$PWD modules

[[ -f meudriver.ko ]] && insmod meudriver.ko

[[ -f ../utilitarios/tool.c ]] && cc ../utilitarios/tool.c -o tool.o

# make clean
